global:
  domain: argocd.example.com
server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    ingressClassName: "nginx-internal"
    hostname: "argocd.example.com"
    tls: true
